- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Car
      ansible.builtin.debug:
       msg: Car
      when: type == "Car"

    - name: Bike
      ansible.builtin.debug:
       msg: Bike
      when: type == "Bike"   
          